config/routes.rb
Tienda::Application.routes.draw do
  
  devise_for :users

  root :to => "products#index"
  
  resources :items

  resources :carts do
    member do
      post :confirm
    end
  end

  resources :products do
    member do 
      post :add_to_cart
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :items
  
  def add_product(product)
    past_item = self.items.where(:product_id => product.id).first
    if past_item.nil?
      self.items.create(:product => product)
    else
      past_item.units += 1
      past_item.save
    end
  end
  
  def total
    total = 0
    self.items.each do |item|
      total += (item.product.price * item.units)
    end
    total
  end
  
  def confirm!
    self.status = 'confirmed'
    self.save
  end
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to  :cart
  belongs_to  :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  has_many    :items
  
  has_attached_file         :image
  
  validates_presence_of     :name, :message => 'El nombre no puede estar en blanco'
  validates_presence_of     :price, :message => 'El precio no puede estar en blanco'
  
  validates_numericality_of :price, :message => 'El precio debe ser un numero'
  validates_numericality_of :units, :allow_blank => true, :message => 'El numero de unidades debe ser un numero'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter  :create_cart
  
  def create_cart
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def show
    
  end
  
  def confirm
    @cart.confirm!
    CartsMailer.confirm(@cart, current_user).deliver
    session[:cart_id] = nil
    flash[:notice] = 'Gracias por tu compra'
    redirect_to products_path
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if !params[:search].blank?
      @products = Product.where('name like ? or description like ?', "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @products = Product.all
    end  
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'El producto se ha creado con &eacute;xito') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'El producto se ha modificado con &eacute;xito') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
  
  def add_to_cart
    @product = Product.find(params[:id])
    @cart.add_product(@product)
    redirect_to products_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<h1>Confirmacion de compra</h1>

<table>
	<tr>
		<th>Producto</th>
		<th>Cantidad</th>
		<th>Precio</th>
	</tr>
		
	<% @cart.items.each do |item| %>
		<tr>
		<td><%= item.product.name %></td>
		<td><%= item.units %></td>
		<td><%= item.product.price %></td>
		</tr>
	<% end %>
	
</table>

<h2>Total: <%= number_to_currency(@cart.total) %></h2>

<%= form_tag confirm_cart_path do %>
	<%= submit_tag 'Confirmar compra' %>
<% end %>

app/views/layouts/_main_menu.html.erb
<ul>
	<% if user_signed_in? %>
		<li><%= link_to "Crear producto", new_product_path %></li>
		<li><%= link_to "Salir", destroy_user_session_path %></li>
	<% else %>
		<li><%= link_to "Entrar", new_user_session_path %></li>
		<li><%= link_to "Registro", new_user_registration_path %></li>
	<% end %>
</ul>

app/views/layouts/_menu.html.erb
<ul class="internal_menu">
	
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tienda</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	
	<div id="header">
		<div class="wrapper">
			<!--LOGO-->
			<div id="logo">
				<a href='/'><h1 style='color:#fff'>Mi super tienda</h1></a>
			</div>
			<!--MENU-->
			<div id="menu">
				<%= render :partial => 'layouts/main_menu' %>
			</div>
		</div>
	</div>

	<!--CONTENTENIDO-->
	<div id="content">
		<div class="wrapper">
			<!--MAIN-->
			
			<div id="main">
				<p>
					
					<div id="hello">
						<% if user_signed_in? %>
							<h2>Bienvenido <%= current_user.first_name %></h2>
						<% end %>
					</div>
					<div id="search">
						<% form_tag(products_path, :method => :get) do %>
						<%= image_submit_tag "buscar.png", :class => 'sbutton' %>
						
							<%= text_field_tag :search, params[:search], :class => 'sbox' %>
						<% end %>
					</div>
				</p>
			</div>
				<!--MENU TIENDA-->
				<div id="ribbon">
					<!--HOME-->
					<div id="menutienda">
						<table width="100%" cellpadding="0" cellspacing="0">
							<tr>
								<td width="35px" style="background:url(/images/home.png) right center no-repeat; text-align: right;">
									<%= link_to image_tag("casa.gif", :alt => "home", :style => 'border:none;'), products_path %>
								</td>
								<td>
									
								</td>
							</tr>
						</table>
					</div>
				</div>
				<!--REST-->
				<div id="rest">
					<!--LEFT-->
					<div id="cleft">
						<!--MINI CART-->
						<div id="minicart" class="spanish_cart">
							<div class="content">
								<%= render :partial => '/products/cart' %>
							</div>
						</div>
					</div>
					<!--RIGHT-->
					<div id="cright">
						<%- flash.each do |name, msg| -%>
					      <%= content_tag :div, msg, :id => "flash_#{name}" %>
					    <%- end -%>
						<%= yield %>
					</div>
				</div>
		</div>
	</div>
</body>
</html>

app/views/products/_cart.html.erb
<% unless @cart.items.empty? %>
	<table>
		<% @cart.items.each do |item| %>
			<tr>
				<td class='cart_name'><%= item.product.name %></td>
				<td class='cart_qty'><%= item.units %></td>
				<td class='cart_price'><%= number_to_currency item.product.price %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="2">Total</td>
			<td class="cart_prc" id="cart_total"><%= number_to_currency @cart.total %></td>
		</tr>
	</table>

	<p>
		<%= link_to image_tag("comprarcarrito.png", :class => 'cartcheckout'), @cart %>
	</p>

	<div class="clearb"></div>
<% else %>
	<p style='padding:10px'>Todav&iacute;a no has comprado nada</p>
<% end %>

app/views/products/_form.html.erb
<%= form_for(@product, :html => {:multipart => true}) do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>Tuviste errores al enviar la forma</h2>
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nombre' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price, 'Precio' %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :units, 'Unidades' %><br />
    <%= f.text_field :units %>
  </div>

  <div class="field">
    <%= f.label :image, 'Imagen' %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    Descripci&oacute;n<br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Crear producto', :class => 'submit' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<% @products.each do |product| %>

	<div class="item">
		<div class="imageholder">
			<%= link_to image_tag(product.image.url), product %>
		</div>
		<p class="name"><%= link_to product.name, product %></p>	
		<p class="price"><%= number_to_currency product.price %></p>
		
		<p>
			<%= link_to 'Agregar al carrito',
			 			 add_to_cart_product_path(product),
			 			:method => :post %>
		</p>
		
	</div>
	
<% end %>

<div class='clearb'></div>

app/views/products/new.html.erb
<div class='form'>
	<h1>Nuevo producto</h1>

	<%= render 'form' %>
		
</div>

app/views/products/show.html.erb
<!--PRODUCTOS-->
<div class="clear">
	<!--FOTO-->
	<div class="left">

		<div class="pic">
			<%= image_tag @product.image.url, :alt => "Picture Not Available" %>
		</div>
	</div>
	<!--DESCRIPCION-->
	<div class="descripcion">
		<h2><%= @product.name %></h2>
		<p><%= @product.description %></p>
		<p><em>Existence: </em><%= @product.units %></p>
		<p class="precio"><%= number_to_currency @product.price %></p>
		<div class="clearb">
			<p>
				<%= link_to 'Agregar al carrito',
				 			 add_to_cart_product_path(@product),
				 			:method => :post %>
			</p>

			<p>
				<%= link_to 'Editar', edit_product_path(@product) %>
				<%= link_to 'Eliminar', @product, :confirm => 'Estas seguro?', :method => :delete %>
			</p>
		</div>
	</div>
                 
</div>